/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import cliente.ClienteRMI;
import modelo.Produto;
import service.EstoqueService;
import javax.swing.JOptionPane;
import java.rmi.RemoteException;
import java.util.List;

/**
 *
 * @author roger
 */
public class FrmReajustarpreco extends javax.swing.JFrame {

    private ClienteRMI clienteRMI;
    private javax.swing.JFrame janelaAnterior;
    
    /**
     * Creates new form FrmReajustarpreco
     */
    public FrmReajustarpreco() {
        initComponents();
        clienteRMI = new ClienteRMI();
        if (!clienteRMI.conectar()) {
            JOptionPane.showMessageDialog(this, 
                "Não foi possível conectar ao servidor RMI.",
                "Erro de Conexão", 
                JOptionPane.ERROR_MESSAGE);
        } else {
            carregarProdutos();
        }
    }
    
    public FrmReajustarpreco(ClienteRMI cliente, javax.swing.JFrame anterior) {
        initComponents();
        this.clienteRMI = cliente;
        this.janelaAnterior = anterior;
        if (!clienteRMI.estaConectado() && !clienteRMI.conectar()) {
            JOptionPane.showMessageDialog(this, 
                "Não foi possível conectar ao servidor RMI.",
                "Erro de Conexão", 
                JOptionPane.ERROR_MESSAGE);
        } else {
            carregarProdutos();
        }
    }
    
    private void carregarProdutos() {
        try {
            EstoqueService service = clienteRMI.getService();
            List<Produto> produtos = service.listarProdutos();
            JCBProduto.removeAllItems();
            for (Produto p : produtos) {
                JCBProduto.addItem(p.getNome());
            }
            if (produtos.size() > 0) {
                JCBProduto.setSelectedIndex(0);
                atualizarPrecoAtual();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar produtos: " + e.getMessage());
        }
    }
    
    private void atualizarPrecoAtual() {
        try {
            EstoqueService service = clienteRMI.getService();
            String nomeProduto = (String) JCBProduto.getSelectedItem();
            if (nomeProduto != null) {
                Produto produto = service.buscarProdutoPorNome(nomeProduto);
                if (produto != null) {
                    JTFPrecoAtual.setText(String.format("%.2f", produto.getPreco()));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar preço: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JCBProduto = new javax.swing.JComboBox<>();
        JTFPrecoAtual = new javax.swing.JTextField();
        JTFPercentual = new javax.swing.JTextField();
        JBAumentar = new javax.swing.JToggleButton();
        JBReduzir = new javax.swing.JToggleButton();
        JBVoltar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Reajuste de preço");

        jLabel2.setText("Produto:");

        jLabel3.setText("Preço atual:");

        jLabel4.setText("Percentual:");

        JCBProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCBProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBProdutoActionPerformed(evt);
            }
        });

        JBAumentar.setText("➕ Aumentar");
        JBAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAumentarActionPerformed(evt);
            }
        });

        JBReduzir.setText("➖ Reduzir");
        JBReduzir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBReduzirActionPerformed(evt);
            }
        });

        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCBProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFPrecoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(JBAumentar)
                        .addGap(18, 18, 18)
                        .addComponent(JBReduzir)
                        .addGap(18, 18, 18)
                        .addComponent(JBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(JCBProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFPrecoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(JTFPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAumentar)
                    .addComponent(JBReduzir)
                    .addComponent(JBVoltar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBProdutoActionPerformed
        atualizarPrecoAtual();
    }//GEN-LAST:event_JCBProdutoActionPerformed

    private void JBAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAumentarActionPerformed
        try {
            double percentual = Double.parseDouble(JTFPercentual.getText());
            if (percentual <= 0) {
                JOptionPane.showMessageDialog(this, "O percentual deve ser maior que zero.");
                return;
            }
            
            EstoqueService service = clienteRMI.getService();
            boolean sucesso = service.reajustarPrecosPercentual(percentual);
            
            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Preços reajustados com sucesso!");
                atualizarPrecoAtual();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao reajustar preços.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um percentual válido.");
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(this, "Erro ao reajustar preços: " + e.getMessage());
        }
    }//GEN-LAST:event_JBAumentarActionPerformed

    private void JBReduzirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBReduzirActionPerformed
        try {
            double percentual = Double.parseDouble(JTFPercentual.getText());
            if (percentual <= 0) {
                JOptionPane.showMessageDialog(this, "O percentual deve ser maior que zero.");
                return;
            }
            
            EstoqueService service = clienteRMI.getService();
            boolean sucesso = service.reajustarPrecosPercentual(-percentual);
            
            if (sucesso) {
                JOptionPane.showMessageDialog(this, "Preços reajustados com sucesso!");
                atualizarPrecoAtual();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao reajustar preços.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um percentual válido.");
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(this, "Erro ao reajustar preços: " + e.getMessage());
        }
    }//GEN-LAST:event_JBReduzirActionPerformed

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        if (janelaAnterior != null) {
            janelaAnterior.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_JBVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReajustarpreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReajustarpreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReajustarpreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReajustarpreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReajustarpreco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JBAumentar;
    private javax.swing.JToggleButton JBReduzir;
    private javax.swing.JToggleButton JBVoltar;
    private javax.swing.JComboBox<String> JCBProduto;
    private javax.swing.JTextField JTFPercentual;
    private javax.swing.JTextField JTFPrecoAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
